package GUI;


// This code was partially generated by Visual for Eclipse (v4all)
//
// *******************************************************************************
// 
// V4ALL for Swing)
// 
// (c) Ramin Assisi, Computer Scientist, Switzerland 2003
// 
// 
// *******************************************************************************
// 




public class probando extends javax.swing.JDesktopPane
{

/**
 * user code fields V4ALL Entry Level
 */
// user code begin FIELDS {1} Swing
// user code end
// user code begin FIELDS {1} SWT
// user code end
// user code begin FIELDS {1} HTML
// user code end
// user code begin FIELDS {1} Eclipse
// user code end
// user code begin FIELDS {1} C#
// user code end

/**
 * user code methods V4ALL Entry Level
 */
// user code begin METHODS {1} Swing
// user code end
// user code begin METHODS {1} SWT
// user code end
// user code begin METHODS {1} HTML
// user code end
// user code begin METHODS {1} Eclipse
// user code end
// user code begin METHODS {1} C#
// user code end


/**
* Initializes connections
* @exception java.lang.Exception The exception description.
*/
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void initConnections() throws java.lang.Exception {
    // user code begin {1} Swing
    // user code end
    // user code begin {1} SWT
    // user code end
    // user code begin {1} HTML
    // user code end
    // user code begin {1} Eclipse
    // user code end
    // user code begin {1} C#
    // user code end
    // user code begin {2} Swing
    // user code end
    // user code begin {2} SWT
    // user code end
    // user code begin {2} HTML
    // user code end
    // user code begin {2} Eclipse
    // user code end
    // user code begin {2} C#
    // user code end
}
/** V4ALL Entry Level
* Return the DesktopPane100 property value.
* @return javax.swing.JDesktopPanel
*/
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private javax.swing.JDesktopPane getDesktopPane100() {
    if (ivjDesktopPane100 == null) {
        try {
           ivjDesktopPane100 = new javax.swing.JDesktopPane();
           ivjDesktopPane100.setBounds(118, 212, 308, 207);
           ivjDesktopPane100.setName("DesktopPane100");
           ivjDesktopPane100.setBackground(new java.awt.Color(153, 153, 204));
           ivjDesktopPane100.setForeground(new java.awt.Color(0, 0, 0));
           ivjDesktopPane100.setFont(new java.awt.Font("Arial", 0, 12));
           ivjDesktopPane100.setOpaque(true);
           ivjDesktopPane100.setLayout(null);
           getDesktopPane100().add(getTabbedPane100(), getTabbedPane100().getName());
           // user code begin {1} Swing
           // user code end
           // user code begin {1} SWT
           // user code end
           // user code begin {1} HTML
           // user code end
           // user code begin {1} Eclipse
           // user code end
           // user code begin {1} C#
           // user code end
        } catch (java.lang.Throwable ivjExc) {
           // user code begin {2} Swing
           // user code end
           // user code begin {2} SWT
           // user code end
           // user code begin {2} HTML
           // user code end
           // user code begin {2} Eclipse
           // user code end
           // user code begin {2} C#
           // user code end
        handleException(ivjExc);
        }
    }
    return ivjDesktopPane100;
}
/** V4ALL Entry Level
* Return the TabbedPane100 property value.
* @return javax.swing.JTabbedPanel
*/
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private javax.swing.JTabbedPane getTabbedPane100() {
    if (ivjTabbedPane100 == null) {
        try {
           ivjTabbedPane100 = new javax.swing.JTabbedPane();
           ivjTabbedPane100.setBounds(30, 39, 213, 153);
           ivjTabbedPane100.setMinimumSize(new java.awt.Dimension(213, 153));
           ivjTabbedPane100.setMaximumSize(new java.awt.Dimension(213, 153));
           ivjTabbedPane100.setName("TabbedPane100");
           ivjTabbedPane100.setBackground(new java.awt.Color(204, 204, 204));
           ivjTabbedPane100.setForeground(new java.awt.Color(0, 0, 0));
           ivjTabbedPane100.setFont(new java.awt.Font("Arial", 0, 12));
           ivjTabbedPane100.setOpaque(true);
           getTabbedPane100().insertTab("Page", null, getPanel100(), "", 0);
           ivjTabbedPane100.setBackgroundAt(0, new java.awt.Color(204, 204, 204));
           ivjTabbedPane100.setForegroundAt(0, new java.awt.Color(0, 0, 0));
           getTabbedPane100().insertTab("Page", null, getPanel101(), "", 1);
           ivjTabbedPane100.setBackgroundAt(1, new java.awt.Color(204, 204, 204));
           ivjTabbedPane100.setForegroundAt(1, new java.awt.Color(0, 0, 0));
           // user code begin {1} Swing
           // user code end
           // user code begin {1} SWT
           // user code end
           // user code begin {1} HTML
           // user code end
           // user code begin {1} Eclipse
           // user code end
           // user code begin {1} C#
           // user code end
        } catch (java.lang.Throwable ivjExc) {
           // user code begin {2} Swing
           // user code end
           // user code begin {2} SWT
           // user code end
           // user code begin {2} HTML
           // user code end
           // user code begin {2} Eclipse
           // user code end
           // user code begin {2} C#
           // user code end
        handleException(ivjExc);
        }
    }
    return ivjTabbedPane100;
}
/** V4ALL Entry Level
* Return the Panel100 property value.
* @return javax.swing.JPanell
*/
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private javax.swing.JPanel getPanel100() {
    if (ivjPanel100 == null) {
        try {
           ivjPanel100 = new javax.swing.JPanel();
           ivjPanel100.setBounds(0, 18, 213, 135);
           ivjPanel100.setMinimumSize(new java.awt.Dimension(213, 135));
           ivjPanel100.setMaximumSize(new java.awt.Dimension(213, 135));
           ivjPanel100.setName("Panel100");
           ivjPanel100.setBackground(new java.awt.Color(204, 204, 204));
           ivjPanel100.setForeground(new java.awt.Color(0, 0, 0));
           ivjPanel100.setFont(new java.awt.Font("Arial", 0, 12));
           ivjPanel100.setOpaque(true);
           ivjPanel100.setLayout(null);
           // user code begin {1} Swing
           // user code end
           // user code begin {1} SWT
           // user code end
           // user code begin {1} HTML
           // user code end
           // user code begin {1} Eclipse
           // user code end
           // user code begin {1} C#
           // user code end
        } catch (java.lang.Throwable ivjExc) {
           // user code begin {2} Swing
           // user code end
           // user code begin {2} SWT
           // user code end
           // user code begin {2} HTML
           // user code end
           // user code begin {2} Eclipse
           // user code end
           // user code begin {2} C#
           // user code end
        handleException(ivjExc);
        }
    }
    return ivjPanel100;
}
/** V4ALL Entry Level
* Return the Panel101 property value.
* @return javax.swing.JPanell
*/
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private javax.swing.JPanel getPanel101() {
    if (ivjPanel101 == null) {
        try {
           ivjPanel101 = new javax.swing.JPanel();
           ivjPanel101.setBounds(0, 18, 213, 135);
           ivjPanel101.setMinimumSize(new java.awt.Dimension(213, 135));
           ivjPanel101.setMaximumSize(new java.awt.Dimension(213, 135));
           ivjPanel101.setName("Panel101");
           ivjPanel101.setBackground(new java.awt.Color(204, 204, 204));
           ivjPanel101.setForeground(new java.awt.Color(0, 0, 0));
           ivjPanel101.setFont(new java.awt.Font("Arial", 0, 12));
           ivjPanel101.setOpaque(true);
           ivjPanel101.setLayout(null);
           // user code begin {1} Swing
           // user code end
           // user code begin {1} SWT
           // user code end
           // user code begin {1} HTML
           // user code end
           // user code begin {1} Eclipse
           // user code end
           // user code begin {1} C#
           // user code end
        } catch (java.lang.Throwable ivjExc) {
           // user code begin {2} Swing
           // user code end
           // user code begin {2} SWT
           // user code end
           // user code begin {2} HTML
           // user code end
           // user code begin {2} Eclipse
           // user code end
           // user code begin {2} C#
           // user code end
        handleException(ivjExc);
        }
    }
    return ivjPanel101;
}


/**
 * Initialize the class.
 */
/* WARNING: THIS METHOD WILL BE REGENERATED. */
private void initialize() {
    try {
        // user code begin {1} Swing
        // user code end
        // user code begin {1} SWT
        // user code end
        // user code begin {1} HTML
        // user code end
        // user code begin {1} Eclipse
        // user code end
        // user code begin {1} C#
        // user code end
        initConnections();
        // user code begin {2} Swing
        // user code end
        // user code begin {2} SWT
        // user code end
        // user code begin {2} HTML
        // user code end
        // user code begin {2} Eclipse
        // user code end
        // user code begin {2} C#
        // user code end
     }
     catch (java.lang.Throwable ivjExc) {
         handleException(ivjExc);
     }
}



/** V4ALL Entry Level
* Called whenever the part throws an exception.
* @param exception java.lang.Throwable
*/
private void handleException(java.lang.Throwable exception) {
	/* Uncomment the following lines to print uncaught exceptions to stdout */
    // System.out.println("--------- UNCAUGHT EXCEPTION ---------");
    // exception.printStackTrace(System.out);
}

private javax.swing.JDesktopPane ivjDesktopPane100 = null;
private javax.swing.JTabbedPane ivjTabbedPane100 = null;
private javax.swing.JPanel ivjPanel100 = null;
private javax.swing.JPanel ivjPanel101 = null;
}


